#+TITLE:Learning Japanese
#+AUTHOR:ICECREAM(氷菓)
#+EMAIL:creamidea(AT)gmail.com
#+OPTIONS:H:4 num:t toc:t \n:nil @:t ::t |:t ^:t f:t TeX:t email:t
#+LINK_HOME: http://creamidea.github.io
#+STYLE:<link rel="stylesheet" type="text/css" href="../css/style.css">
#+INFOJS_OPT: 

#+BEGIN_HTML
---
layout: doc
title: Learning Japanese
subtitle: 初学者学习日语笔记 
categories: note
tags: language japanese
---
#+END_HTML

* 前言
上学期期末的时候，受同宿舍小杰同学的影响，开始看日本动漫，发现日本二维动漫做的的确不错。
忽略某些日本动漫，大部分日本动漫做的的确不错。这个产业如同那些西方欧美国家的电视剧和电影
制作一样，完全产业化，链条上的每一方都是可以从中获利。

扯远了，其实我只是慢慢地发现日语其实也是值得去学习一下的。嗯，就是这个样子。

算到现在以《新版 标准本日语》这本教材为准的话，那么现在（<2013-04-08 月曜日>）已经学习到第五课了。
感觉当初那个学习日语的激情正在慢慢减弱，为了防止自己虎头蛇尾，现在开始写这个笔记。
记录每一课的主要语法和一些说日语的习惯。另外关于生词我会不定期贴在每课的后面。
这篇日记也会不定期的更新。

*小知识:*

第（だい）一（いっ）課（か）。

科目(科目)：今日(きょう)の午後（ごご）私は授業（じゅぎょう）があります。
今天下午我有课。

如何输入促音：输入两遍后面一个音2遍。例：第１課、”いっか”的输入：ikka。

* 第１課<2013-04-08 月曜日>
** 基本语法
1. [名]は [名]です
2. [名]は [名]では　ありません
3. [名]は [名]ですか
4. [名] の [名]
   
** 表达及词语讲解
** 小知识
** 单词 

* 第５課<2013-04-08 月曜日>
** 基本语法
1. 今　～時　～分です

2. 现在：[动]ます　[动]ません        
   过去：[动]ました　[动]ませんでした
   #+BEGIN_EXAMPLE
	* 五段动词（1类动词）
	* 五段动词：动词词尾只有一个假名，最后一个假名为
          う段中9个假名中的一个。
	* 变化规则：同行的变成い段 + ます
	* 例子： 行（ぎょ）く　--> 行きます   
   #+END_EXAMPLE

   #+BEGIN_EXAMPLE
	* 一段动词（2类动词）
	* 一段动词：以る结尾， 前面为い， え段
	* 变化规则：去掉る， 添加 ます
	* 例子： 食（しょく）ベる　-->　食べます   
   #+END_EXAMPLE

   #+BEGIN_EXAMPLE
	* サ变（3类动词）
	* サ变：
	* 变化规则：（词干）+ する --> （词干）+ し + ます
	* 例子： 勉強する　-->　勉強します   
   #+END_EXAMPLE

   #+BEGIN_EXAMPLE
	* カ变
	* カ变：　
	* 例子（就一个）： 来る（くる） -->　　来ます（きます）
   #+END_EXAMPLE
   *以上参考网站：*
   1. http://zhidao.baidu.com/question/33998558.html

   2. http://baike.baidu.com/view/2349826.htm

   3. http://bulo.hujiang.com/question/10779/

3. 名[时间]に  动
   #+BEGIN_EXAMPLE
    表示动作发生的时间, 在具体时间后面要加上に
	- 森さんは　七時に　起きます
	今　昨日　今日　明日　毎日　去年　来年　等后面不加　に
    星期后面一般加に， 也可以不加
    - 日曜日に
   #+END_EXAMPLE

4. 名[时间]から  名[时间]まで 动
   #+BEGIN_EXAMPLE
    表示动作发生在某个时期
    - 私は　くじ　から　ごじ　まで　働(はたら)きます　我9点到5点工作   
   #+END_EXAMPLE

5. いつ　动ますか
   #+BEGIN_EXAMPLE
    询问某动作或时态进行的时间
   #+END_EXAMPLE

6. は[对比]

** 表达及词语讲解
** 小知识
** 单词 
#+BEGIN_EXAMPLE
#+INCLUDE: "~/Documents/Language/日本語/words/5.txt"
#+END_EXAMPLE

* 第６課<2013-04-08 月曜日>
** 基本语法
   1. 名【场所】へ 动:
      使用 =行きます= =帰ります= 等表示移动的动词时，移动行为的目的地用助词 =へ= ，这时的 =へ= 读做 =え= 　
      - 森さんは　日本へ　帰ります。 森先生回日本。
   2. 名【场所】から 动:
      使用移动动词时，移动的起点用助词 =から= 
      - 李さんは　先月（せんげつ）　北京から　来（き）ました。　李先生上月从北京来。
   3. 名【人】と 动:
      共同做某事的时候用助词 =と= 
   4. 名【交通工具】で 动:
      交通工具使用助词 =で= ， 不使用交通工具时，使用歩（ある）いて
      - わたしは　バスで　家（いえ）へ　帰（かえ）ります。 我乘坐公共汽车回家。
   5. 名【场所】から 名【场所】まで 动:
      表示移动的范围
      - 森せんは　東京（とうきょう）から　広島（ひろしま）まで　新幹線（しんかんせん）で　行（い）きます。
        
        森先生从东京乘坐新干线去广岛。
** 表达及词语讲解
** 小知识
** 单词 

* 第？課
** 基本语法
** 表达及词语讲解
** 小知识
** 单词   



